/*!50003 DROP PROCEDURE IF EXISTS `remove_win_device` */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = latin1 */ ;
/*!50003 SET character_set_results = latin1 */ ;
/*!50003 SET collation_connection  = latin1_swedish_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
CREATE PROCEDURE `remove_win_device`(did bigint unsigned)
BEGIN
	DELETE FROM windowsos WHERE deviceid = did;
	DELETE FROM computersystem WHERE deviceid = did;
	DELETE FROM computerhardware WHERE deviceid = did;
	DELETE FROM windowsnetwork WHERE deviceid = did;
	DELETE FROM windowsdisks WHERE deviceid = did;
	DELETE FROM windowsphysicaldisk WHERE deviceid = did;
	DELETE FROM windowsapplications WHERE deviceid = did;
	DELETE FROM windowsapplicationregistry WHERE deviceid = did;
	DELETE FROM windowsprocessor WHERE deviceid = did;
	DELETE FROM win_cpu_info WHERE deviceid = did;
	DELETE FROM windowsservices WHERE deviceid = did;
	DELETE FROM windowsshares WHERE deviceid = did;
	DELETE FROM windowskey WHERE deviceid = did;
	DELETE FROM windowsprocess WHERE deviceid = did;
	DELETE FROM windowsconnection WHERE deviceid = did;
	DELETE FROM windowsdnscache WHERE deviceid = did;
	DELETE FROM winperfcpu WHERE deviceid = did;
	DELETE FROM winperfmem WHERE deviceid = did;
	DELETE FROM winperfdisk WHERE deviceid = did;
	DELETE FROM winperfphysdisk WHERE deviceid = did;
	DELETE FROM winperfdisk_rawdata WHERE deviceid = did;
	DELETE FROM winperfnet WHERE deviceid = did;
	DELETE FROM win_dns WHERE deviceid = did;
	DELETE FROM win_dns_a_record WHERE deviceid = did;
	DELETE FROM win_dns_c_name WHERE deviceid = did;
	DELETE FROM http_get_inventory WHERE deviceid = did;
	DELETE FROM terminalservices WHERE deviceid = did;
	DELETE FROM terminalservicessession WHERE deviceid = did;
	DELETE FROM citriximanetworking WHERE deviceid = did;
	DELETE FROM citrixlicensing WHERE deviceid = did;
	DELETE FROM citrixmetaframepresentationserver WHERE deviceid = did;
	DELETE FROM icasession WHERE deviceid = did;
END ;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
